apiVersion: apps/v1
kind: Deployment
metadata:
  name: passion-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passion-app
  template:
    metadata:
      labels:
        app: passion-app
    spec:
      containers:
        - name: passion-app
          image: public.ecr.aws/f9g5b7l3/passion-app:latest
          ports:
            - containerPort: 8080
